### ISSUE TITLE
Supporting mio library

### ISSUE THREAD

**Issue by Susurrus** [dcuddeback/serial-rs#11]
The [mio](https://github.com/carllerche/mio) library supports asynchronous I/O for UDP and higher-level protocols. I'd love to use it with serial-rs as well to support serial-to-UDP or serial-to-TCP applications easily. Have you looked at that framework at all?

**Comment by dcuddeback** [comment]
Hi @Susurrus. I am familiar with `mio`, but I have no plans to integrate it directly into `serial`, because it introduces a dependency that not everyone is going to want to have in their project. It should be possible to integrate `serial` with `mio` by writing an extension crate (e.g., `mio-serial`). Serial ports in the `serial` crate already expose their underlying file descriptor (or Window handle), which should be enough to integrate with other I/O libraries, such as `mio`. I have no plans to write a `serial` integration for `mio` in the near future, so please feel free to spearhead that project if it interests you and let me know if there's anything that's needed from the `serial` crate to make that possible.

Closing this issue since the integration should happen in a separate project, but feel free to reopen if it requires changes to `serial`.
