### ISSUE TITLE
read timeout with Arduino

### ISSUE THREAD

**Issue by fuchsnj** [dcuddeback/serial-rs#2]
I'm trying to use this library with an Arduino Nano. I am able to open the COM port on Windows (the Arduino resets itself when this happens) but I am unable to read anything from the port. I set the port timeout to 1000 milliseconds, but whenever I read I immediately get "operation timed out".
Any ideas?

**Comment by dcuddeback** [comment]
Nothing immediately springs to mind as a potential cause. I tested the Windows implementation with an [Aeon Labs Z-Stick](http://www.amazon.com/Aeon-Labs-DSA02203-ZWUS-Z-Wave-Z-Stick/dp/B003MWQ30E) dongle, and I was able to read a response from it. I have a couple other serial devices that I can experiment with later this week to see if I can replicate the timeout issue.

I found this forum thread which suggests that the Arduino might reset when the DTR line is toggled (http://forum.arduino.cc/index.php?topic=48577.0). When testing with a FTDI chip, I noticed that the DTR and RTS lines toggle when opening a COM port. If I'm not mistaken, this is controlled by the driver.

**Comment by dcuddeback** [comment]
@fuchsnj I did some research on Arduinos this morning. It looks like resetting when opening the port is intentional. It appears to be how the IDE loads new code into the flash memory.
- http://playground.arduino.cc/Learning/AutoResetRetrofit gives some details on how Arduino's auto-reset feature works.
- http://playground.arduino.cc/Main/DisablingAutoResetOnSerialConnection shows how to disable it with a pull-up resistor. It starts out, "So you have found need for disabling the auto reset? So that the arduino does not reset when establishing a connection."

Is resetting the Arduino when opening the serial port a different behavior than you observe with other serial port libraries?

**Comment by fuchsnj** [comment]
@dcuddeback sorry for any misunderstanding. I said the arduino reset when it connected to show that it did indeed connect to the right port. I was fully expecting it to reset. My problem is actually reading data from the Arduino. It might just be a problem with configuring the right settings, but the default settings (the ones in the README.md) seemed to be the same as Arduino. I'm playing around with it now to see if I can figure out what was wrong.

**Comment by fuchsnj** [comment]
Everything is working for me now... I'm not able to reproduce my problem anymore. No idea what was wrong. I guess I can close this issue now.  Thank you for this awesome library!

**Comment by dcuddeback** [comment]
@fuchsnj Okay. I thought you were reporting two problems. Glad to hear everything's working now. :) Feel free to reopen the issue if you see the premature timeout again.
