### ISSUE TITLE
Clarity on cloning port settings to a new port

### ISSUE THREAD

**Issue by Susurrus** [dcuddeback/serial-rs#28]
I'm writing code that will change the underlying port when the user requests it. That means I want to copy the current port settings, overwrite the current port reference I have with a new one of the new port, and apply the copied settings to the new port. It's unclear to me as to what the best way to do this is given the `configure()`, `reconfigure()` functions, and the `read_settings()` and `write_settings()` functions. I would have thought the following would work, but I think I'm misunderstanding the API somewhat as this doesn't give the expected behavior:

``` rust
// port is an Option<Box<serial::SystemPort>>
if port.is_some() {
    println!("Changing port to {}", name);
    let old_port = port.unwrap();
    let new_settings = (*old_port).read_settings().unwrap();
    let mut p = Box::new(serial::open(&name).unwrap());
    p.write_settings(&new_settings).unwrap();
    port = Some(p);
}
```

**Comment by dcuddeback** [comment]
Copying settings from one port to another isn't supported per-se (since it's unspecified whether the settings type has references to its particular hardware), but I don't see why it wouldn't work with the current implementation.

Did you try `configure()` or `reconfigure()`? The documentation for `SerialDevice` says that it's "a trait for _implementing_ serial devices." You're meant to use the `SerialPort` trait in application code. That's why it's in the prelude and `SerialDevice` is not.

That said, you didn't really tell me what didn't work or any details about the platform you're running on, so I can't offer any more advice than to try `configure()` or `reconfigure()`.

**Comment by Susurrus** [comment]
There's kind of a couple of things at work here that got wrapped up into this one issue and I'd like to separate them a bit as I don't think I was very clear before. 

First off the documentation isn't clear as to what the difference between configure or reconfigure is. It seems like the only difference is the input arguments, but from the names I'd assume configure() could only be run once after open() and reconfigure() can be run n times after configure is called. But no caveats like that are documented. And no recommended method to configure the ports are suggested. As a user of these functions more guidelines on their usage would be very helpful. A question I have is why would anyone want a closure to configure the ports besides setting things directly? That would be a useful question to answer in the docs.

Additionally I don't believe there is a way to "roundtrip" settings where you can copy them from a port and apply them to a new port since there's nothing like `read_settings()` in the SerialPort trait. Can you suggest how I might use (re)configure to do this? I'm running on Linux x64 and Rust 1.9 and I can provide further example code if it would help, but I didn't know how much code would be helpful and how Mich wouldn't be so I just included a little snippit. Any help here would be appreciated.
