### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by Susurrus** [dcuddeback/serial-rs#39]
There hasn't been any commits since July 9th to this project. I'm depending on this project for my gattii software and have been waiting for serial enumeration to stabilize, though there doesn't seem to be any progress here. Are you still actively developing this project where your work has just been private so far or is it safe to consider this abandoned?

**Comment by dcuddeback** [comment]
Hi again. Definitely not abandoned. Just been spending my free time doing other things recently. I have lots of project ideas that will rely on serial ports, so rest assured that I will pick up work on this project again when my hobbies pull me in that direction. Since this project isn't my 9-5 job, please don't expect to see a continuous stream of commits. I believe you said that you were enumerating serial ports within your project until I've added it here, so I'll rest easy knowing that this isn't a blocker for you.

**Comment by Susurrus** [comment]
I understand this isn't something you're focused on, which is why I was asking. One of the last comments I got from you was that you were in the middle of a big rewrite, so I assumed that was still getting time. The reason I bring this is up is because I can't post my crate to crates.io until all its dependencies have released versions also on crates.io. I was considering forking this project and pushing development along that way if this wasn't seeing much development from you and that isn't expected to change in the next few months.
