### ISSUE TITLE
public interface changes depending on operating system

### ISSUE THREAD

**Issue by fuchsnj** [dcuddeback/serial-rs#4]
Right now the `open` function returns a different type depending on if you compile for Linux / Windows.
This makes it more difficult to write cross-platform code using this library. A better approach would be to have a struct that represents a generic serial port . Then each operating system would provide a different implementation of the `SerialPort` trait for this common struct. This allows cross-platform code to be written using the generic serial port struct without caring how it was implemented, instead of having `TTYPort`, and `COMPort`.

**Comment by dcuddeback** [comment]
@fuchsnj My intention was for people to use the `SerialPort` trait instead of referring directly to the system-specific types. The reason for this is that I want the library to be extensible for people to write custom implementations, such as an IP-to-serial bridge. (Eventually, I'd like the trait to support embedded systems as well, but that's dependent on `#![no_std]` becoming stable.)

Admittedly, using the trait as an generic object doesn't work at the moment, because the `Settings` associated type differs for each implementation. I'm planning on fixing that, as it will improve the usability a lot, especially for another major feature that I want to implement: listing available ports. I don't know yet what that solution will look like. In the mean time, cross-platform code can be written with generics:

``` rust
fn say_hello<T: SerialPort>(port: &mut T) -> io::Result<()> {
    try!(port.write("hello".as_bytes()));
    Ok(())
}

struct Driver<T: SerialPort> {
    port: T
}
```

I'll leave this issue open as motivation to make `SerialPort` usable as a trait object.

**Comment by dcuddeback** [comment]
@fuchsnj I made some changes in v0.2.0 that will allow you to use the `SerialPort` as a trait object. So now if you don't want to deal with generics, you can use `&SerialPort` or `Box<SerialPort>`.
