### ISSUE TITLE
Full duplex read-write in two threads

### ISSUE THREAD

**Issue by thejpster** [dcuddeback/serial-rs#40]
I'd like to read from a port in one thread (in a blocking fashion) while handling writes in a second thread. I don't believe I can do this with a single SerialPort object that implements both Read and Write.

The way `std::sync::mpsc` solves the problem is to have two objects: an RX and a TX object.

Does that sound like a good approach? Is there another way to split my reads and writes between two threads?

**Comment by SirVer** [comment]
I have a similar and probably related problem: I'd like to read full lines from serial ports, for that I have to wrap it in something that implements `BufRead`, but I cannot use `std::io::BufReader` since that consumes my serial - and then I cannot write to it anymore. Some rust libraries provide a `split` for objects that can be a reader and a writer so you can share there responsibilities.

**Comment by dcuddeback** [comment]
@thejpster There's a bit more discussion about this topic in #21. I even got a proof-of-concept going in the [`feature/try-clone`](https://github.com/dcuddeback/serial-rs/compare/feature/try-clone) branch, which I linked to in that issue. As I recall, the implementation was a little hacky and no one is sure if it will work on other Unix platforms or if the same can be done with Windows handles.

I like the idea of splitting `Read` and `Write` like `std::sync::mpsc` (I think that idea was also discussed in #21), but it's not clear which interface the control lines (RTS, DTR, etc) belong to.

@SirVer Splitting read/write or allowing ports to be cloned should make `BufReader` usable. One of the solutions proposed in #21 (simply marking the serial ports as `Sync`) wouldn't.

I'd like to consolidate this ticket with #21. Please feel free to continue the discussion on that ticket. I'm closing this one to cut down on duplicates.
