### ISSUE TITLE
Only works one time ?

### ISSUE THREAD

**Issue by firefixmaarten** [dcuddeback/serial-rs#5]
Hi,
I'm using this command to setup 2 connected virtual ports:
# socat -d -d pty,raw,echo=0,crnl pty,raw,echo=0,crnl

Then i run the test program, al goes fine.
I run the testingprogram again, i Got an error.
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(16) }', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:729

If i Kill the virtual COM ports and use the setup command again it works 1 time.
is the port not correctly closed or access is being reset?

 // get exclusive access to device
-        try!(ioctl::tiocexcl(port.fd));
  +

Maybe this commit created the problem ?

**Comment by dcuddeback** [comment]
@firefixmaarten Thanks for reporting this issue. I was able to reproduce it with `socat` on Linux. Oddly, I don't run into this problem with `socat` on OS X or using physical hardware on Linux or OS X.

The problem does seem to be caused by the `TIOCEXCL` ioctl, which gives the program exclusive access to the device. I'll add a `TIOCNXCL` ioctl to the destructor to release exclusive mode. That should fix the issue that you're having as long as the program terminates normally.

**Comment by dcuddeback** [comment]
@firefixmaarten Do you want to give it a try with v0.1.2?

**Comment by firefixmaarten** [comment]
@dcuddeback:

It works like advised now. Thanks!
