### ISSUE TITLE
Disable timeout

### ISSUE THREAD

**Issue by SoniEx2** [dcuddeback/serial-rs#51]
How do I disable timeout?

**Comment by dcuddeback** [comment]
It's not supported. You can get essentially the same behavior by setting the timeout with a large `Duration` if you'd like, but I don't recommend ignoring timeouts.

**Comment by SoniEx2** [comment]
https://bitbucket.org/SoniEx2/wcc-rs/src/e07c866224a84accda05fa7fd4d956a185daabf7/src/lib.rs?at=master&fileviewer=file-view-default#lib.rs-221

**Comment by stbuehler** [comment]
This is a deal breaker imho in varios ways:

- it's not the "common" way rust deals with IO; to use timeouts you should integrate it into `futures`, so you can use a proper event loop, in other words: `Read::read` shouldn't do more than it is supposed to
- From reading (simple) source code using `serial` it is completely unclear that there is a hidden timeout of ~~one second~~ 100 milliseconds, making debugging way harder than it should be.  The timeout should at least be explicit in the constructor (or a `read_with_timeout` function), don't use a "random" default value.
- `read` should *never* return `0` due to a timeout; returning `0` for a non-empty buffer always means end of file (the only "exception" is that end of file doesn't have to be a permanent state).
- I'd like to avoid the unnecessary syscall because timing is important to me (reading DCF77)
- Imho `VMIN` should at least be `1`.  I'd hope that for non-blocking reads `O_NONBLOCK` should work on serial ports, which is the correct solution.
