### ISSUE TITLE
How do I read more than one byte at a time?

### ISSUE THREAD

**Issue by anthonyclays** [dcuddeback/serial-rs#6]
This may very well be because I simply don't fully understand how the `Read` trait is supposed to work.

Running this code:

``` rust
let mut buf: Vec<u8> = vec![0u8; 50];
println!("{}", port.read(&mut buf[0..50]).unwrap());
```

only '1' to the screen. `buf` contains the first byte received at index 0, and the original zeros are still at indices 1:49.

I would expect that the port should read 50 bytes into the given buffer, as there is no way to pass the number of bytes to read... ? What am I doing wrong here?

For reference, I'm sending this:

``` rust
debug_assert!(port.write("*idn?\n".as_bytes()).unwrap() == 6);
```

over a usb -> rs232 converter, which sends back a 50-byte identification string (tested using pyserial).

Furthermore, I was able to read all bytes one by one and print them out using a for loop:

``` rust
for _ in 0..50 {
    port.read(&mut buf[0..50]).unwrap();
    print!("{}", buf[0] as char);
}
```

but that isn't exactly a solution to the problem.

**Comment by michaelsproul** [comment]
I think this is partly just the nature of serial devices, rather than anything specific to this library. I'm seeing very similar behaviour with my own USB serial device, although occasionally I get a 2 byte read!

Your usage for the `Read` trait is perfectly fine, for files and other immediately available data sources you could expect larger reads. Using a loop seems perfectly reasonable.

If you look at [the source](https://github.com/dcuddeback/serial-rs/blob/master/src/posix/tty.rs), most of the work is done by the `read` system call (so the behaviour is determined by the OS and the device).

**Comment by anthonyclays** [comment]
Thanks for the explanation. A quick note, `std::io` contains a few structs that are very helpful: `BufReader`, `BufWriter` and `BufStream` (read + write, unstable). It offloads the buffering of input/output streams, and it's really pleasant to work with (see in particular `fill_buf`, `read_line` and `read_until` in the trait `BufRead`).

I'm closing this as it's no longer an issue.

**Comment by dcuddeback** [comment]
@anthonyclays It sounds like you found a solution, but I think I can give some background on what's likely happening.

`read()` returns as soon as there is any data available in the operating system's receive buffer. If you call `read()` while data is being transmitted, you'll only receive the data that has already arrived. For example, 50 bytes at 9600 baud takes about 50ms to transmit. If you call `read()` after 1ms, you'll probably only receive one or two bytes, because the rest of the bytes are still being sent.

You can test if this is happening by inserting a sleep before calling `read()`. If you sleep long enough for all the data to be transmitted, you should get all 50 bytes in a single call to `read()`. I don't recommend this as a general solution in production code, but just as a test to understand what's happening.

The same is true for TCP sockets, but the rate of data transmission is typically much faster than serial ports, so the effect is less noticeable.

**Comment by anthonyclays** [comment]
Thank you for the explanation - that makes a lot of sense.
Setting a timeout of 1 second and wrapping the serial port in BufStream (so I can use `readuntil`) appears to be exactly what I needed.
Cheers!
